language: python
python: 3.7.2
dist: xenial
install:
  - pip install -r requirements.txt
  - pip install .
jobs:
  include:
    - stage: Unit Tests With Coverage
      script: pytest --cov=clashboard --cov-fail-under=90
    - stage: Style Check
      script: pycodestyle src tests
addons:
  ssh_known_hosts:
  - 18.218.152.78
before_deploy:
- openssl aes-256-cbc -K $encrypted_454b0e6863c5_key -iv $encrypted_454b0e6863c5_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- chmod 600 deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i deploy_rsa ubuntu@18.218.152.78 'source /home/ubuntu/clashboard/scripts/deploy.sh'
